# 自定义异常、NullPointerException、断言

## 自定义异常
### Java标准库异常  
![](https://i.loli.net/2021/11/14/CTP1SUXMGwE8Ymt.png)

我们在代码中需要抛出异常的时候，尽量使用JDK已经定义的异常类型       

### 自定义异常  
我们可以自定义新的异常类型，但是，保持一个合理的异常继承体系是非常重要的        
一个常见的做法是**自定义**一个```BaseException```作为“根异常”，然后，派生出各种业务类型的异常。 
一般而言，我们建议从```RuntimeException```中派生出```BaseException```,然后再从这里派生出其它业务类型的异常   

```Java
public class BaseException extends RuntimeException{

}
//------------------------------------------------------

public class UserNotFoundException extends BaseException{
    //...
}

public class LoginFailedException extends BaseException{
    //...
}
```

自定义的```BaseException```应该提供多个构造方法 
```Java
public class BaseException extends RuntimeException {
    public BaseException() {
        super();
    }

    public BaseException(String message, Throwable cause) {
        super(message, cause);
    }

    public BaseException(String message) {
        super(message);
    }

    public BaseException(Throwable cause) {
        super(cause);
    }
}
``` 
上述构造方法实际上都是原样照抄RuntimeException。这样，抛出异常的时候，就可以选择合适的构造方法。通过IDE可以根据父类快速生成子类的构造方法。     

## NullPointerException

### 介绍
```NullPointerException```即空**指针异常**，俗称NPE。如果一个对象为null，调用其方法或访问其字段就会产生NullPointerException，这个异常通常是由JVM抛出的  

> 指针这个概念实际上源自C语言，Java语言中并无指针。我们定义的变量实际上是引用，Null Pointer更确切地说是Null Reference，不过两者区别不大 

### 处理
首先，必须明确，NullPointerException是一种代码逻辑错误，遇到NullPointerException，遵循原则是**早暴露，早修复**

**严禁使用catch来隐藏这种编码错误** 

1.好习惯，比如成员变量在定义时就进行初始化，这样自然就不会null了
> 编写业务逻辑时，用空字符串""表示未填写比null安全得多

2.一步步寻找null的地方。有意思的是Java 14增加了直接爆出null所在位置的功能，可以看情况手动开启   

## 断言 Assertion   
断言（Assertion）是一种调试程序的方式。在Java中，使用assert关键字来实现断言 

### 例子与使用  
```Java
public static void main(String[] args) {
    double x = Math.abs(-123.45);
    assert x >= 0;
    System.out.println(x);
}
```
在这里，```assert x >= 0;```即为断言,它表明着“x >= 0 ”的预期结果是true，如果结果是false，则认为断言失败，抛出一个```AssertionError```   

使用assert语句时，还可以添加一个可选的断言消息：
```asser x >= 0 : "x must >= 0"```
这样，在断言失败的时候，就会带上**x must >= 0**的消息，便于我们调试 

### 特点
Java断言的特点是：断言失败时会抛出AssertionError，导致程序结束退出  

因此，断言不能用于可恢复的程序错误，只应该用于开发和测试阶段
而且，对于可恢复的程序错误，不应该使用断言，而应该抛出异常并在上层捕获  

另外，JVM默认关闭断言指令，即遇到assert语句就自动忽略了，不执行。
> 要执行assert语句，必须给Java虚拟机传递-enableassertions（可简写为-ea）参数启用断言    

**断言很少被使用，更好的方法是编写单元测试**